---
vlan_01:
  accounting: { id: '30', subnet: 10.1.30.0/24, root: dist-sw01 }
  management: { id: '31',  subnet: 10.1.31.0/24, root: dist-sw01 }
  voice01: { id: '10', subnet: 10.1.10.0/24, root: dist-sw01 }

vlans: "{{ vlan_01|combine(vlan_02) }}"

# Specify a range or individual port to be trunk or access.
# If you wanted to implement port-channel, just add the 'group' attribute
# in the list of dictionaries.
access_ports:
  - ports:
      - 'Gi1/0 - 1'
      - 'Gi2/0'
    data: accounting
    voice: voice01
  - ports:
      - 'Gi1/2 - 3'
    data: management
    voice: voice01

trunk_ports:
  - { group: 1, ports: ['Gi0/0 - 1'], description: -> dist-sw01 }
  - { group: 2, ports: ['Gi0/2 - 3'], description: -> dist-sw02 }

allowed_vlans: "{{ vlans.values()|map(attribute='id')|list|join(',') }}"
